[package]
name = "hakoniwa"
version = "1.1.0"
description = "Process isolation for Linux using namespaces, resource limits and seccomp."
keywords = ["security", "sandbox", "sandboxing", "process-isolation", "linux-namespaces"]
homepage = "https://github.com/souk4711/hakoniwa"
repository = "https://github.com/souk4711/hakoniwa"
license = "LGPL-3.0-linking-exception"
readme = "../README.md"
edition = "2021"

[dependencies]
bincode = { version = "2.0.0-rc.3", features = ["serde"] }
fastrand = "2.3.0"
libc = "0.2.169"
nix = { version = "0.29.0", features = ["fs", "hostname", "mount", "process", "resource", "sched", "signal", "user"] }
os_pipe = "1.2.1"
serde = { version = "1.0.217", features = ["derive"] }
thiserror = "2.0.11"

[dev-dependencies]
assertables = "9.5.0"
