[package]
name = "hakoniwa"
version = "1.1.0"
description = "Process isolation for Linux using namespaces, resource limits and seccomp."
keywords = ["security", "sandbox", "sandboxing", "process-isolation", "linux-namespaces"]
homepage = "https://github.com/souk4711/hakoniwa"
repository = "https://github.com/souk4711/hakoniwa"
license = "LGPL-3.0-linking-exception"
readme = "../README.md"
edition = "2021"
