[package]
name = "hakoniwa"
version = "0.3.0"
description = "Process isolation for Linux using namespaces, resource limits and seccomp."
homepage = "https://github.com/souk4711/hakoniwa"
repository = "https://github.com/souk4711/hakoniwa"
license = "MIT OR Apache-2.0"
readme = "../README.md"
edition = "2021"

[dependencies]
bincode = { version = "2.0.0-rc.1", features = ["serde"] }
chrono = { version = "0.4.20", features = ["serde"] }
fastrand = "1.8.0"
handlebars = "4.3.3"
lazy_static = "1.4.0"
libc = "0.2.126"
libseccomp = "0.2.3"
log = "0.4.17"
nix = "0.25.0"
path_abs = "0.5.1"
serde = { version = "1.0.140", features = ["derive"] }
serde_json = "1.0.83"
thiserror = "1.0.31"
toml = "0.5.9"
