namespaces = [
  { type = "cgroup"  },
  { type = "ipc"     },
  { type = "network" },
  { type = "uts"     },
]

mounts = [
  { source = "/bin"   },
  { source = "/etc"   },
  { source = "/lib"   },
  { source = "/lib64" },
  { source = "/sbin"  },
  { source = "/usr"   },
  { source = "/opt"   },
  { source = ""        , destination = "/dev", type = "devfs" },
  { source = ""        , destination = "/tmp", type = "tmpfs" },
  { source = ""        , destination = "/run", type = "tmpfs" },
  { source = ""        , destination = "/sys", type = "tmpfs" },
]

envs = [
  { name = "LANG"     },
  { name = "LANGUAGE" },
]

landlock.resources = [
  { type = "fs"          },
  { type = "tcp.bind"    },
  { type = "tcp.connect" },
]

landlock.fs = [
  { path = "/"     , access = "r--" },
  { path = "/bin"  , access = "r-x" },
  { path = "/etc"  , access = "r--" },
  { path = "/lib"  , access = "r-x" },
  { path = "/lib64", access = "r-x" },
  { path = "/sbin" , access = "r-x" },
  { path = "/usr"  , access = "r--" },
  { path = "/opt"  , access = "r-x" },
  { path = "/dev"  , access = "rw-" },
  { path = "/tmp"  , access = "rw-" },
  { path = "/run"  , access = "rw-" },
  { path = "/sys"  , access = "rw-" },
  { path = "/proc" , access = "rw-" },
  { path = "/home" , access = "rw-" },
]
