"@include" = [
  "abstractions/base.toml",
]

mounts = [
  { source = "/var/lib/pacman" },
  { source = "{{ HOME }}/.local/share/hakoniwa/apps/makepkg", destination = "{{ HOME }}", rw = true },
  { source = "{{ PWD }}", destination = "/home/makepkg", rw = true },
]

envs = [
  { name = "HOME"        },
  { name = "PATH"        },
  { name = "ALL_PROXY"   },
  { name = "HTTP_PROXY"  },
  { name = "HTTPS_PROXY" },
]

[[landlock.fs]]
path = "/home/makepkg"
access = "rwx"

[network]
mode = "pasta"
options = ["-T", "auto"]

[command]
cmdline = ["/bin/makepkg"]
cwd = "/home/makepkg"
