mounts = [
  { source = "/dev/null"   , target = "/dev/null"     , rw = true },
  { source = "/dev/random" , target = "/dev/random"  },
  { source = "/dev/urandom", target = "/dev/urandom" },
  { source = "/dev/zero"   , target = "/dev/zero"    },
  { source = "/bin"        , target = "/bin"         },
  { source = "/lib"        , target = "/lib"         },
  { source = "/lib64"      , target = "/lib64"       },
  { source = "/usr"        , target = "/usr"         },
]

[env]
TERM = {{ os_env "TERM" }}
