mount_new_tmpfs = true
mount_new_devfs = true
mounts = [
  { source = "/bin"  , target = "/bin"  },
  { source = "/lib"  , target = "/lib"  },
  { source = "/lib64", target = "/lib64"},
  { source = "/usr"  , target = "/usr"  },
]

[env]
TERM = {{ os_env "TERM" }}
