[[mounts]]
source = "/bin"
target = "/bin"

[[mounts]]
source = "/lib"
target = "/lib"

[[mounts]]
source = "/lib64"
target = "/lib64"

[[mounts]]
source = "/usr"
target = "/usr"

[env]
TERM = {{ os_env "TERM" }}
