mounts = [
  { source = "/bin"  , target = "/bin"  },
  { source = "/lib"  , target = "/lib"  },
  { source = "/lib64", target = "/lib64"},
  { source = "/usr"  , target = "/usr"  },
]

[limits]
as = 256000000  # 256MB
core = 0        # no core file
cpu = 2         # 2 seconds
fsize = 0       # no output file
nofile = 32     # 32 max fd
walltime = 5    # 5 seconds

[seccomp]
syscalls = [
  "access",
  "arch_prctl",
  "brk",
  "clock_gettime",
  "close",
  "connect",
  "eventfd2",
  "execve",
  "exit_group",
  "fcntl",
  "getcwd",
  "getdents64",
  "getegid",
  "geteuid",
  "getgid",
  "getpid",
  "getrandom",
  "getuid",
  "ioctl",
  "lseek",
  "mmap",
  "mprotect",
  "munmap",
  "newfstatat",
  "openat",
  "prctl",
  "pread64",
  "prlimit64",
  "read",
  "readlink",
  "rseq",
  "rt_sigaction",
  "rt_sigprocmask",
  "sched_getaffinity",
  "set_robust_list",
  "set_tid_address",
  "sigaltstack",
  "socket",
  "timer_create",
  "timer_delete",
  "writev",
]
