[package]
name = "hakoniwa-cli"
version = "0.4.6"
description = "Process isolation for Linux using namespaces, resource limits and seccomp."
keywords = ["security", "sandbox", "sandboxing", "process-isolation", "linux-namespaces"]
homepage = "https://github.com/souk4711/hakoniwa"
repository = "https://github.com/souk4711/hakoniwa"
license = "MIT OR Apache-2.0"
readme = "../README.md"
edition = "2021"

[dependencies]
clap = { version = "3.2.13", features = ["derive"] }
env_logger = "0.9.0"
lazy_static = "1.4.0"
log = "0.4.17"
rust-embed = "6.4.0"
serde_json = "1.0.83"
thiserror = "1.0.31"

[dependencies.hakoniwa]
version = "0.4.6"
path = "../hakoniwa"

[[bin]]
name = "hakoniwa"
path = "src/main.rs"
