[package]
name = "hakoniwa-cli"
version = "1.1.0"
description = "Process isolation for Linux using namespaces, resource limits and seccomp."
keywords = ["security", "sandbox", "sandboxing", "process", "process-isolation", "linux-namespaces"]
homepage = "https://github.com/souk4711/hakoniwa"
repository = "https://github.com/souk4711/hakoniwa"
license = "GPL-3.0-only"
readme = "../README.md"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.29", features = ["derive"] }
clap-verbosity-flag = "3.0.2"
env_logger = "0.11.6"
lazy_static = "1.5.0"
log = "0.4.25"

[dependencies.hakoniwa]
version = "1.1.0"
path = "../hakoniwa"

[dev-dependencies]
trycmd = "0.15.9"

[[bin]]
name = "hakoniwa"
path = "src/main.rs"
