"@include" = [
  "abstractions/base.toml",
  "abstractions/dbus-session.toml",
  "abstractions/dbus-system.toml",
  "abstractions/x11.toml",
  "abstractions/audio.toml",
  "abstractions/graphics.toml",
]

namespaces = [
  { type = "network", share = true },
]

mounts = [
  { source = "{{ HOME }}/.local/share/hakoniwa/apps/firefox", destination = "{{ HOME }}", rw = true },
  { source = "{{ HOME }}/Downloads", rw = true },
]

envs = [
  { name = "HOME" },
]

[network]
mode = "pasta"
options = ["-T", "auto"]

[command]
cmdline = ["firefox"]
cwd = "{{ HOME }}"
