"@include" = [
  # --rootfs
  "abstractions/rootfs.toml",

  # --unshare-all
  "abstractions/unshare-all.toml",
]

mounts = [
  # --devfs /dev --tmpfs /tmp
  { source = "", destination = "/dev", type = "devfs" },
  { source = "", destination = "/tmp", type = "tmpfs" },

  # -B "$HAKONIWA_DATA_HOME/apps/fish":"$HOME"
  { source = "{{ HOME }}/.local/share/hakoniwa/apps/fish", destination = "{{ HOME }}", rw = true },
]

envs = [
  # -e HOME
  { name = "HOME" },

  # -e TERM
  { name = "TERM" },
]

# -- fish
[command]
cmdline = ["/bin/fish"]
