share_net = true

mounts = [
  { source = "/bin"  , target = "/bin"  },
  { source = "/lib"  , target = "/lib"  },
  { source = "/lib64", target = "/lib64"},
  { source = "/usr"  , target = "/usr"  },
  { source = "/etc/resolv.conf", target = "/etc/resolv.conf" },
]

[seccomp]
dismatch_action = "allow"
syscalls = [
  "listen",
]
