[limits]
# as = 256000000  # use GOMEMLIMIT
core = 0        # no core file
cpu = 2         # 2 seconds
fsize = 0       # no output file
nofile = 16     # 16 max fd
walltime = 5    # 5 seconds

[env]
GOMEMLIMIT = "256000000"
