share_uts = true

mounts = [
  { source = "/bin"  , target = "/bin"  },
  { source = "/lib"  , target = "/lib"  },
  { source = "/lib64", target = "/lib64"},
  { source = "/usr"  , target = "/usr"  },
  { source = "/dev"  , target = "/dev"  },
  { source = "/tmp/.X11-unix"               , target = "/tmp/.X11-unix"      , rw = true },
  { source = {{ os_homedir "/.Xauthority" }}, target = "/hako/.Xauthority"  },
]

[env]
DISPLAY    = {{ os_env "DISPLAY" }} # :0
XAUTHORITY = "/hako/.Xauthority"
HOME       = "/hako"
