share_net = true
share_uts = true

mounts = [
  { source = "/bin"       , target = "/bin"        },
  { source = "/lib"       , target = "/lib"        },
  { source = "/lib64"     , target = "/lib64"      },
  { source = "/usr"       , target = "/usr"        },
  { source = "/dev/null"  , target = "/dev/null"    , rw = true },
  { source = "/dev/random", target = "/dev/random" },
  { source = "/dev/snd"   , target = "/dev/snd"    },
  { source = "/etc/fonts"      , target = "/etc/fonts"       },
  { source = "/etc/machine-id" , target = "/etc/machine-id"  },
  { source = "/etc/resolv.conf", target = "/etc/resolv.conf" },
  { source = "/tmp/.X11-unix"  , target = "/tmp/.X11-unix"    , rw = true },
  { source = {{ os_homedir "/.mozilla"    }}, target = {{ os_homedir "/.mozilla"    }}  , rw = true },
  { source = {{ os_homedir "/.Xauthority" }}, target = {{ os_homedir "/.Xauthority" }} },
  { source = {{ os_homedir "/Downloads"   }}, target = {{ os_homedir "/Downloads"   }}  , rw = true },
]

[env]
DISPLAY    = {{ os_env "DISPLAY"    }} # :0
XAUTHORITY = {{ os_env "XAUTHORITY" }} # /home/johndoe/.Xauthority
HOME       = {{ os_env "HOME"       }} # /home/johndoe
