mounts = [
  { source = "/bin"  , target = "/bin"  },
  { source = "/lib"  , target = "/lib"  },
  { source = "/lib64", target = "/lib64"},
  { source = "/usr"  , target = "/usr"  },
]

[seccomp]
syscalls = [
  "access",
  "arch_prctl",
  "brk",
  "close",
  "execve",
  "exit_group",
  "getrandom",
  "ioctl",
  "mmap",
  "mprotect",
  "munmap",
  "newfstatat",
  "openat",
  "pread64",
  "prlimit64",
  "read",
  "rseq",
  "set_robust_list",
  "set_tid_address",
  "write",
]
