# --unshare-all
namespaces = [
  { type = "cgroup"  },
  { type = "ipc"     },
  { type = "network" },
  { type = "uts"     },
]

# --rootfs
mounts = [
  { source = "/bin"   },
  { source = "/etc"   },
  { source = "/lib"   },
  { source = "/lib64" },
  { source = "/sbin"  },
  { source = "/usr"   },
]

mounts = [
  # --devfs /dev --tmpfs /tmp
  { source = "", destination = "/dev", type = "devfs" },
  { source = "", destination = "/tmp", type = "tmpfs" },

  # -B "$HAKONIWA_DATA_HOME/apps/fish":"$HOME"
  { source = "{{ HOME }}/.local/share/hakoniwa/apps/fish", destination = "{{ HOME }}", rw = true },
]

envs = [
  # -e HOME
  { name = "HOME" },

  # -e TERM
  { name = "TERM" },
]

# -- /bin/fish
[command]
cmdline = ["/bin/fish"]
