share_uts = true

mounts = [
  { source = "/bin"  , target = "/bin"   },
  { source = "/lib"  , target = "/lib"   },
  { source = "/lib64", target = "/lib64" },
  { source = "/usr"  , target = "/usr"   },
  { source = "/etc/fonts"    , target = "/etc/fonts"   },
  { source = "/tmp/.X11-unix", target = "/tmp/.X11-unix", rw = true },
  { source = {{ os_env "XDG_RUNTIME_DIR"   }}, target = {{ os_env "XDG_RUNTIME_DIR"   }}  , rw = true },
  { source = {{ os_homedir "/.config"      }}, target = {{ os_homedir "/.config"      }}  , rw = true },
  { source = {{ os_homedir "/.local/share" }}, target = {{ os_homedir "/.local/share" }} },
  { source = {{ os_homedir "/.Xauthority"  }}, target = {{ os_homedir "/.Xauthority"  }} },
  { source = {{ os_homedir "/Documents"    }}, target = {{ os_homedir "/Documents"    }} },
  { source = {{ os_homedir "/Downloads"    }}, target = {{ os_homedir "/Downloads"    }} },
  { source = {{ os_homedir "/Videos"       }}, target = {{ os_homedir "/Videos"       }} },
  { source = {{ os_homedir "/Music"        }}, target = {{ os_homedir "/Music"        }} },
  { source = {{ os_homedir "/Pictures"     }}, target = {{ os_homedir "/Pictures"     }} },
]

[env]
DISPLAY                     = {{ os_env "DISPLAY"                     }} # :0
DESKTOP_SESSION             = {{ os_env "DESKTOP_SESSION"             }} # plasma
QT_AUTO_SCREEN_SCALE_FACTOR = {{ os_env "QT_AUTO_SCREEN_SCALE_FACTOR" }} # 0
XDG_CURRENT_DESKTOP         = {{ os_env "XDG_CURRENT_DESKTOP"         }} # KDE
XDG_RUNTIME_DIR             = {{ os_env "XDG_RUNTIME_DIR"             }} # /run/user/5001
XDG_SESSION_TYPE            = {{ os_env "XDG_SESSION_TYPE"            }} # x11
XDG_SESSION_DESKTOP         = {{ os_env "XDG_SESSION_DESKTOP"         }} # KDE
XAUTHORITY                  = {{ os_env "XAUTHORITY"                  }} # /home/johndoe/.Xauthority
HOME                        = {{ os_env "HOME"                        }} # /home/johndoe
